site_name: Chi-Wiki

repo_name: 'lushuyu/Chi-Wiki'
repo_url: 'https://github.com/lushuyu/Chi-Wiki'

# Copyright
copyright: 'Copyright &copy; 2019 Lu Shuyu'

theme:
  name: material
  palette:
    primary: 'Orange'
    accent: 'Blue'
  feature:
    tabs: true
  language: 'zh'
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'
  

nav:
  - 首页: index.md
  - 语文基础知识:
      - 成语辨析: 语文基础知识/成语辨析.md
  - 文言文: 
      - 文言虚词: 文言文/文言虚词.md
      - 古代文化常识: 文言文/古代文化常识.md
  - 学习经验:
      - 济海-知乎: 学习经验/济海-知乎.md

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
      #emoji_generator: !!python/name:pymdownx.emoji.to_svg
      #emoji_generator: !!python/name:pymdownx.emoji.to_png_sprite
      #emoji_generator: !!python/name:pymdownx.emoji.to_svg_sprite
      #emoji_generator: !!python/name:pymdownx.emoji.to_awesome
      #emoji_generator: !!python/name:pymdownx.emoji.to_alt
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

extra:
  social:
    - type: github
      link: https://github.com/lushuyu
  search:
    language: 'jp'
  disqus: 'Chi-Wiki'
  copyright: '<a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh">CC BY-SA 4.0</a> 和 <a href="https://github.com/zTrix/sata-license">SATA</a>'
  pagetime: 'on'
  manifest: 'manifest.webmanifest'
  githash: ''



extra_javascript:
  - 'js/extra.js'
  - 'js/baidu-tongji.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'